// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcFootballTeams.Data;

namespace MvcFootballTeams.Migrations
{
    [DbContext(typeof(MvcFootballTeamsContext))]
    partial class MvcFootballTeamsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcFootballTeams.Models.FootballTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DomesticRank");

                    b.Property<DateTime>("Founded");

                    b.Property<string>("League");

                    b.Property<string>("Name");

                    b.Property<int>("UefaRank");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("FootballTeam");
                });
#pragma warning restore 612, 618
        }
    }
}
